language: r
script:
  - R CMD build . --no-manual --no-build-vignettes
  - R CMD check *tar.gz --no-manual --no-build-vignettes --ignore-vignettes --no-examples
repos:
  CRAN: https://cloud.r-project.org
  BioCsoft: https://bioconductor.org/packages/devel/bioc
  BioCann: https://bioconductor.org/packages/devel/data/annotation
  BioCexp: https://bioconductor.org/packages/devel/data/experiment
r_github_packages:
  - jokergoo/ComplexHeatmap
env:
  - _R_CHECK_FORCE_SUGGESTS_=false